"""Textos do lado Python (avisos, selos, métodos) e glossário padrão, em português (padrão) e inglês."""

TXT = {
    "pt": {
        "nao_registrado": "não registrado", "versao_nr": "versão não registrada", "programa_nr": "programa não registrado",
        "declarado": "declarado na configuração", "declarado_cfg": "declarado na configuração (não lido de arquivo)",
        "digitado": "número digitado na configuração", "sem_fonte": "sem fonte", "principal": "principal",
        "geom_inicial": "geometria inicial", "ranking": "Ranking", "titulo_padrao": "Painel dos cálculos",
        "av_sem_arquivo": "nenhum arquivo encontrado para {}", "av_sem_geometria": "{}: o arquivo não traz geometria",
        "av_inicial": "{}: geometria inicial ilegível ({})", "av_json_vivo": "{}: JSON de acompanhamento ilegível ({})",
        "av_termo": "termo {} (variante {}): {}", "av_termo_tipo": "termo de energia sem 'estrutura', 'json' ou 'valor'",
        "av_sem_energia": "a estrutura {} não tem energia lida", "av_sem_freq": "{}: sem frequências no arquivo",
        "av_comparar": "comparação de frequências {} × {}: sistema ausente",
        "av_mistura": "C-073 · '{}' {} mistura resultados de níveis de cálculo diferentes: {}",
        "crit_padrao_vivo": "critério presumido (EPS_SCF = 1e-6 do CP2K); declare 'criterio' na configuração da fila",
        "m_nivel": "Nível / método", "m_funcional": "Funcional", "m_base": "Base", "m_dispersao": "Dispersão", "m_corte": "Corte de energia",
        "m_pseudo": "Pseudopotenciais", "m_scf": "Algoritmo do SCF", "m_linha": "Linha de comando", "m_hessiana": "Hessiana",
        "m_tarefa": "Tarefa (MLIP)", "m_modelo": "Modelo", "m_programa": "Programa", "m_crit_scf": "Critério do SCF",
        "m_crit_opt": "Critério da otimização", "m_carga": "Carga / multiplicidade", "m_usado": "Usado em",
    },
    "en": {
        "nao_registrado": "not recorded", "versao_nr": "version not recorded", "programa_nr": "program not recorded",
        "declarado": "declared in the configuration", "declarado_cfg": "declared in the configuration (not read from a file)",
        "digitado": "number typed in the configuration", "sem_fonte": "no source", "principal": "main",
        "geom_inicial": "initial geometry", "ranking": "Ranking", "titulo_padrao": "Calculation dashboard",
        "av_sem_arquivo": "no file found for {}", "av_sem_geometria": "{}: the file has no geometry",
        "av_inicial": "{}: unreadable initial geometry ({})", "av_json_vivo": "{}: unreadable live JSON ({})",
        "av_termo": "term {} (variant {}): {}", "av_termo_tipo": "energy term without 'estrutura', 'json' or 'valor'",
        "av_sem_energia": "structure {} has no energy", "av_sem_freq": "{}: no frequencies in the file",
        "av_comparar": "frequency comparison {} × {}: missing system",
        "av_mistura": "C-073 · '{}' {} mixes results from different levels of theory: {}",
        "crit_padrao_vivo": "assumed criterion (CP2K EPS_SCF = 1e-6); declare 'criterio' in the queue configuration",
        "m_nivel": "Level / method", "m_funcional": "Functional", "m_base": "Basis", "m_dispersao": "Dispersion", "m_corte": "Energy cutoff",
        "m_pseudo": "Pseudopotentials", "m_scf": "SCF algorithm", "m_linha": "Command line", "m_hessiana": "Hessian",
        "m_tarefa": "Task (MLIP)", "m_modelo": "Model", "m_programa": "Program", "m_crit_scf": "SCF criterion",
        "m_crit_opt": "Optimization criterion", "m_carga": "Charge / multiplicity", "m_usado": "Used in",
    },
}

GLOSSARIO = {
    "pt": [
        ("DFT", "Teoria do funcional da densidade: calcula a energia de um sistema a partir da densidade de elétrons. É o 'cálculo quântico' mais usado; lento, mas confiável quando o funcional é adequado."),
        ("Funcional e base", "O funcional (PBE, B3LYP, B97-3c...) é a aproximação para a interação entre elétrons; a base (def2-SVP, TZV2P, ondas planas com corte...) é o conjunto de funções que descreve os orbitais. Juntos definem o 'nível de cálculo'."),
        ("MLIP", "Potencial interatômico de aprendizado de máquina (UMA, MACE, CHGNet...): uma rede neural treinada em milhões de cálculos DFT que estima energia e forças em segundos. Deve ser conferido contra DFT no sistema de interesse."),
        ("Nível de cálculo (selo)", "Toda energia vale só para o método com que foi calculada. Por isso cada resultado deste painel traz um selo com o nível e o programa, lidos do próprio arquivo de saída."),
        ("SCF", "Ciclo autoconsistente: o programa ajusta os orbitais repetidamente até que a energia e a densidade parem de mudar. Cada iteração aparece como um ponto no gráfico de convergência."),
        ("Critério de convergência do SCF", "Limite abaixo do qual o SCF é considerado convergido. Cada programa compara uma grandeza diferente: no CP2K (OT) é a coluna 'Convergence' contra EPS_SCF; no ORCA, ΔE e a variação da densidade; no VASP, ΔE contra EDIFF; no pw.x, a 'estimated scf accuracy' contra conv_thr."),
        ("Otimização de geometria", "Sequência de passos em que os átomos se movem na direção em que a energia cai, até as forças ficarem pequenas. O 'filme' mostra esse caminho."),
        ("fmax", "A maior força restante sobre um átomo (eV/Å). Uma otimização termina quando fmax fica abaixo do critério escolhido."),
        ("σ (tensão)", "Tensão interna de um cristal (GPa). Com a célula livre, a otimização também ajusta a caixa até a tensão ficar pequena."),
        ("Célula e supercélula", "A célula unitária é a caixa que se repete para formar o cristal; a supercélula mostra várias cópias lado a lado para enxergar a vizinhança."),
        ("|Δr|", "Quanto cada átomo se moveu da geometria inicial até a final (descontada a translação/rotação de moléculas ou a deformação da célula)."),
        ("Frequência vibracional", "Cada modo normal é um jeito coletivo de os átomos vibrarem, com uma frequência (cm⁻¹). Uma frequência imaginária (negativa) indica que a geometria não é um mínimo naquela direção (ou ruído numérico)."),
        ("ZPE", "Energia de ponto zero: a energia vibracional que resta mesmo a 0 K, soma de metade de cada frequência."),
        ("Perfil de energia", "Diagrama dos níveis de energia relativos (reagentes, intermediários, estados de transição, produtos) ou das parcelas de um ciclo termodinâmico."),
        ("Energia de interação", "Diferença entre a energia do complexo e a soma das partes isoladas; negativa quando a associação é favorável. Sem correção de BSSE e sem ZPE, salvo indicação."),
        ("Confôrmeros / microestados", "Arranjos diferentes do mesmo sistema. O ranking compara as energias relativas; barras de erro mostram a dispersão entre réplicas (partidas diferentes)."),
        ("Exploratório", "Resultado preliminar, ainda não validado: serve para orientar, não para concluir."),
    ],
    "en": [
        ("DFT", "Density functional theory: computes the energy from the electron density. The most common quantum-chemical method; slower, but reliable when the functional is adequate."),
        ("Functional and basis", "The functional (PBE, B3LYP, B97-3c...) approximates electron–electron interaction; the basis (def2-SVP, TZV2P, plane waves with a cutoff...) describes the orbitals. Together they define the 'level of theory'."),
        ("MLIP", "Machine-learning interatomic potential (UMA, MACE, CHGNet...): a neural network trained on millions of DFT calculations that predicts energies and forces in seconds. Check it against DFT on your system."),
        ("Level of theory (badge)", "An energy is only meaningful for the method that produced it. Every result here carries a badge with the level and program, read from the output file itself."),
        ("SCF", "Self-consistent field: the program updates the orbitals until energy and density stop changing. Each iteration is a point on the convergence plot."),
        ("SCF convergence criterion", "Threshold below which the SCF is converged. Each program compares a different quantity: CP2K (OT) compares the 'Convergence' column with EPS_SCF; ORCA, ΔE and the density change; VASP, ΔE against EDIFF; pw.x, the 'estimated scf accuracy' against conv_thr."),
        ("Geometry optimization", "A sequence of steps moving atoms downhill in energy until forces are small. The 'movie' shows this path."),
        ("fmax", "Largest remaining force on an atom (eV/Å). An optimization stops when fmax drops below the chosen threshold."),
        ("σ (stress)", "Internal stress of a crystal (GPa). With a free cell, the box is also optimized until the stress is small."),
        ("Cell and supercell", "The unit cell is the repeating box of a crystal; a supercell shows several copies side by side."),
        ("|Δr|", "How far each atom moved from the initial to the final geometry (rigid translation/rotation of molecules or cell deformation removed)."),
        ("Vibrational frequency", "Each normal mode is a collective vibration with a frequency (cm⁻¹). An imaginary (negative) frequency means the geometry is not a minimum along that mode (or numerical noise)."),
        ("ZPE", "Zero-point energy: vibrational energy left even at 0 K, half the sum of the frequencies."),
        ("Energy profile", "Diagram of relative energy levels (reactants, intermediates, transition states, products) or of the terms of a thermodynamic cycle."),
        ("Interaction energy", "Energy of the complex minus the sum of the isolated parts; negative when association is favourable. No BSSE correction or ZPE unless stated."),
        ("Conformers / microstates", "Different arrangements of the same system. The ranking compares relative energies; error bars show the spread between replicas (different starting points)."),
        ("Exploratory", "Preliminary, not yet validated result: useful for guidance, not for conclusions."),
    ],
}
